name: Flutter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Setup Flutter SDK with a specific version
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5' # Replace with the desired Flutter version

      # Setup Dart SDK with a specific version
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.3.0' # Replace with the desired Dart SDK version

      - name: Install dependencies
        run: flutter pub get

      # Uncomment this step to verify the use of 'flutter format' on each commit.
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test
